# Question 1


In [46]:
s = set(["aman", "222", 777, 400.4])
tup = tuple(s)
print(tup)
print(type(tup))

(400.4, 777, 'aman', '222')
<class 'tuple'>


# Question 2


In [47]:
dict = {'roll' : 20208,
        'name' : 'Aravind',
        'dob' : '08-05-02'}
print(dict)

{'roll': 20208, 'name': 'Aravind', 'dob': '08-05-02'}


# Question 3


In [48]:
arr2 = np.random.randint(9,size=(2,4))
arr2

array([[5, 3, 0, 4],
       [2, 4, 4, 7]])

# Question 4


In [49]:
import random
num = random.randint(1,10)
print(num)
print(abs(-1234))

8
1234


# Question 5


In [ ]:
num = random.randint(20,90)
print(num)

# Question 6


In [40]:
import random
list1=[11, 12, 13,14, 15]

newlist1=random.sample(list1,3)
print(newlist1)

[14, 12, 15]


In [60]:

nparray=np.array(list1)
np.random.shuffle(nparray)

In [42]:
print(nparray)

[13 12 14 11 15]


In [43]:
newlist1=random.sample(list1,1)

In [44]:
print(newlist1)

[13]


# Question 7


# Question 8


In [ ]:
def ch(n):
    if n == 1:
        print('one')
    elif n == 2:
        print('two')
    else:
        print('not 1 or 2')

def ran(n):
    for i in range(n):
        print(i)
        
print('enter choice')
ch(int(input()))

print('enter range :')
ran(int(input()))

enter choice


 1


one
enter range :


 2


0
1


# Question 9


In [51]:
str = "The King is Dead, Long Live The King"
print(str)
print(str[0])
print(str[2:5])
print(str[2:])
print(str.split(' '))

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


# Question 10


In [52]:
arr = list([1,4,5,8])
print(arr[0:2])

[1, 4]


# Question 11

In [4]:
import numpy as np

In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
print(arr1)

[[1 2 3]
 [4 5 6]]


# Question 12


In [11]:
print(arr1[1])

[4 5 6]


In [26]:
a1rr = arr1.astype('float64')
print(arr1[0:2,1])


[2 5]


In [16]:
print(arr1.size)

6


In [17]:
print(arr1.shape)

(2, 3)


# Question 13

In [36]:
arr=[1,2,3,4,5,6,7,8,9,10]
arr2=np.array(arr)
newarr = arr2.reshape(2, 5)
print(newarr)
newarr1 = arr2.reshape(5, 2)
print(newarr1)
print("Transpose")
print(newarr.transpose())
print(newarr1.transpose())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transpose
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


# Question 14

In [19]:
list1 = [1,2,3]

In [22]:
nparray=np.array(list1)

In [24]:
print(nparray)
print(type(nparray))

[1 2 3]
<class 'numpy.ndarray'>


# Question 15

In [25]:
nparray[0]=9
nparray[1]=9
nparray[2]=9
print(nparray)
print(type(nparray))

[9 9 9]
<class 'numpy.ndarray'>


# Question 16

In [59]:
arr = [2,4,5]
print(sum(arr))

11


# Question 17

In [58]:
arr = [77,74,75]
prod = 1
for i in arr:
    prod*=i
print(prod)

427350


# Question 18

In [57]:
arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
# mean, variance, max, min, argmin, median, argmax and standard deviation
print('Mean : ', arr.mean())
print('var : ', arr.var())
print('max : ', arr.max())
print('min ; ', arr.min())
print('argmin : ', arr.argmin())
print('median : ', np.median(arr))
print('argmax : ', arr.argmax())
print('sd : ', np.std(arr))

Mean :  12.461538461538462
var :  367.32544378698225
max :  56
min ;  1
argmin :  1
median :  2.0
argmax :  12
sd :  19.165736192147232


# Question 19

In [56]:
li = [1, 1, 4, 5, 5, 5, 7]
uniq = list(set(li))
uniq.sort()
print(uniq)

[1, 4, 5, 7]


# Question 20

In [55]:
li1 = [1, 2, 3]
li2 = [0, 1, 1]

prod = 0

for i in range(len(li1)):
    temp = li1[i]*li2[i]
    prod+=temp
    
print(prod)

5


# Question 21

In [54]:
matA = [[1, -12], [1, -5]]

eigenVal, eigenVect = np.linalg.eig(matA)

print('eigen values : ', eigenVal)
print('eigen vectors : ', eigenVect)

eigen values :  [-2.+1.73205081j -2.-1.73205081j]
eigen vectors :  [[0.96076892+0.j         0.96076892-0.j        ]
 [0.24019223-0.13867505j 0.24019223+0.13867505j]]


# Question 22

In [53]:
li1 = np.array([11, 22, 11, 31])
li2 = np.array([25, 33, 31, 28])

ret = np.corrcoef(li1,li2)
print(ret)

[[1.         0.15997968]
 [0.15997968 1.        ]]
